creation_rules:
  #   - path_regex: (\.(env|nix|conf|toml|tfstate|tfvars|json)$|tfstate\.backup$|.*_SECRET|configuration\.yml|users_database\.yml)
  #     age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3

  - path_regex: \.env$
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3

  - path_regex: \.json$
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3
    encrypted_regex: >-
      ^(address|id|serverName|password|shortId|target|serverNames|shortIds|privateKey)$

  - path_regex: (\.tfstate$|tfstate\.backup$)
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3

  - path_regex: \.tfvars$
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3
    encrypted_regex: >-
      ^(zone_id|account_id|domain)$

  - path_regex: users_database\.yml$
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3
    encrypted_regex: >-
      ^(password|email)$

  # - path_regex: configuration\.yml$
  #   age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3
  #   encrypted_regex: >-
  #     ^(password|passwd|secret|token|api_key|access_key|secret_key|
  #     private_key|client_secret|passphrase|auth_token|signing_key|
  #     encryption_key|jwt_secret|session_secret|webhook_secret|key)$

  #   - path_regex: \.ya?ml$
  #     age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3
  #     encrypted_regex: >-
  #       ^(password|passwd|secret|token|api_key|apikey|access_key|secret_key|
  #       private_key|client_secret|passphrase|auth_token|signing_key|
  #       encryption_key|master_key|jwt_secret|session_secret|webhook_secret|
  #       service_account_key|credentials|private|connection_string|key)$

  - path_regex: (publickey|privatekey|presharedkey)-.*
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3

  - path_regex: .*_SECRET$
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3

  - path_regex: \.nix$
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3

  - path_regex: \.conf$
    age: age13vz3u6zjv44a4ak4r2qmdaydh4s0l4yfhywhsvzzhg9p5rn004pqsy8gx3
