volumes:
  traefik-le-data:

networks:
  infra:
    external: true
  netbird:
    external: true

services:
  traefik:
    image: traefik:v3.6.12
    container_name: traefik
    restart: always
    env_file:
      - .env
    networks:
      infra:
      netbird:
        ipv4_address: 172.30.0.10
    security_opt:
      - no-new-privileges:true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command:
      # debug
      - "--accesslog=true"
      - "--log.level=INFO"

      # docker config
      - "--providers.docker=true"
      - "--providers.docker.network=infra"
      - "--providers.docker.exposedbydefault=false"

      # turns
      - "--entrypoints.turns.address=:5349"

      # grpc
      - "--entrypoints.https.transport.respondingTimeouts.readTimeout=0"
      - "--entrypoints.https.transport.respondingTimeouts.writeTimeout=0"
      - "--entrypoints.https.transport.respondingTimeouts.idleTimeout=0"
      - "--serverstransport.forwardingtimeouts.responseheadertimeout=0s"
      - "--serverstransport.forwardingtimeouts.idleconntimeout=0s"
      - "--providers.file.filename=/etc/traefik/dynamic.yaml"

      # https
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http3=true"
      - "--entrypoints.https.http.tls.certresolver=le"
      - "--certificatesresolvers.le.acme.email=admin@lxft.dev"
      - "--certificatesresolvers.le.acme.storage=/le/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=8.8.8.8:53"
      - "--certificatesresolvers.le.acme.dnsChallenge.propagation.delayBeforeChecks=60"
      - "--certificatesresolvers.le.acme.dnschallenge.propagation.disableChecks=true"
    ports:
      - "443:443"
      - "443:443/udp"
      - "5349:5349"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    volumes:
      - traefik-le-data:/le
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml:ro
