networks:
  infra:
    external: true

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:100
    networks:
      - infra
    restart: unless-stopped
    environment:
      ND_EXTAUTH_TRUSTEDSOURCES: 0.0.0.0/0
      ND_EXTAUTH_USERHEADER: "Remote-User"
      ND_EXTAUTH_ADMINROLEHEADER: "Remote-Groups"
      ND_EXTAUTH_ADMINROLE: "admins"
      ND_ENABLEUSEREDITING: false
      ND_EXTAUTH_ALLOWUSERCREATION: "true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.music.entrypoints: "websecure"
      traefik.http.routers.music.rule: "Host(`music.lxft.dev`)"
      traefik.http.routers.music.middlewares: authelia@docker
      traefik.http.routers.music.tls.certresolver: "le"
      traefik.http.services.music.loadbalancer.server.port: "4533"
      traefik.http.routers.music-public.rule: Host(`music.lxft.dev`) && (PathPrefix(`/share/`) || PathPrefix(`/rest/`))
      traefik.http.routers.music-public.entrypoints: https
    volumes:
      - "./data:/data"
      - "./music:/music:ro"
