server {
  listen 443 ssl;
  listen 443 quic;
  server_name waka.lxft.tech;

  http2 on;
  http3 on;
  quic_gso on;
  quic_retry on;
  add_header Alt-Svc 'h3=":443"; ma=86400';

  ssl_certificate /certs/waka.lxft.tech.crt;
  ssl_certificate_key /certs/waka.lxft.tech.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_ecdh_curve X25519:prime256v1:secp384r1;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;

  server_tokens off;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;

  client_header_timeout 5m;
  keepalive_timeout 5m;

  location / {
        proxy_pass http://10.8.0.3:13000;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 10m;
        proxy_send_timeout 10m;
        proxy_hide_header X-Powered-By;
        proxy_hide_header Server;
    }
}
