services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - "./.lego/certificates:/certs:ro"
      - "./conf.d:/etc/nginx/conf.d:ro"
    ports:
      - "443:443"
      - "443:443/udp"

  xray:
    image: ghcr.io/xtls/xray-core:latest
    restart: always
    command: run -c /etc/xray/xray.json
    volumes:
      - "./xray.json:/etc/xray/xray.json:ro"
