networks:
  infra:
    external: true

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - infra
    labels:
      traefik.enable: "true"

      traefik.http.routers.lab.entrypoints: "https"
      traefik.http.routers.lab.rule: "Host(`lab.lxft.dev`)"
      traefik.http.routers.lab.tls.certresolver: "le"
      traefik.http.services.lab.loadbalancer.server.port: "80"

  xray:
    image: ghcr.io/xtls/xray-core:latest
    restart: always
    command: run -c /etc/xray/config.json
    volumes:
      - "./config.json:/etc/xray/config.json:ro"
    ports:
      - "5224:5224"
      - "8443:8443"
