networks:
  infra:
    external: true

volumes:
  cobalt-valkey:

services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:11

    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt

    ports:
      - 9000:9000

    environment:
      # API_URL: "https://cobalt.lxft.dev/"
      API_URL: "http://localhost:9000/"
      COOKIE_PATH: "/cookies.json"
      CUSTOM_INNERTUBE_CLIENT: "TV"
      YOUTUBE_SESSION_SERVER: "http://cobalt-pot-generator:4416"
      YOUTUBE_SESSION_INNERTUBE_CLIENT: "WEB_EMBEDDED"
      YOUTUBE_ALLOW_BETTER_AUDIO: "1"
      # API_KEY_URL: "file:///keys.json"
      # HTTPS_PROXY: "https://xray:10808"
      # HTTP_PROXY: "http://xray:10808"
      API_REDIS_URL: "redis://cobalt-valkey:6379"

    volumes:
      - ./keys.json:/keys.json:ro
      - ./cookies.json:/cookies.json:ro

    networks:
      - infra

    depends_on:
      valkey:
        condition: service_healthy
      generator:
        condition: service_started

    labels:
      traefik.enable: "true"
      traefik.http.routers.cobalt.entrypoints: "websecure"
      traefik.http.routers.cobalt.rule: "Host(`cobalt.lxft.dev`)"
      traefik.http.routers.cobalt.tls.certresolver: "le"
      traefik.http.services.cobalt.loadbalancer.server.port: "9000"

  valkey:
    container_name: cobalt-valkey
    image: valkey/valkey:alpine
    networks:
      - infra
    environment:
      - TZ=Europe/Moscow
    volumes:
      - cobalt-valkey:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  generator:
    image: brainicism/bgutil-ytdlp-pot-provider:1.3.1-deno
    init: true
    restart: unless-stopped
    container_name: cobalt-pot-generator
    networks:
      - infra
