#!/bin/sh
set -e

find . \( \
  -name "*.env" -o \
  -name "*.conf" -o \
  -name "secrets.nix" -o \
  -name "secrets.toml" -o \
  -name "publickey-*" -o \
  -name "privatekey-*" -o \
  -name "presharedkey-*" -o \
  -name "config.json" -o \
  -name "*.tfvars" -o \
  -name "*_SECRET" -o \
  -name "*.tfstate" -o \
  -name "*.tfstate.backup" -o \
  -name "configuration.yml" -o \
  -name "users_database.yml" \
\) | grep -v backups | grep -v '\.enc$' | while read -r file; do
  enc_file="${file}.enc"
  echo "Encrypting $file → $enc_file"
  sops -e "$file" > "$enc_file"
  git add "$enc_file"
done
