#!/bin/sh
set -e

find . \( \
  -name "*.env" -o \
  -name ".env*" -o \
  -name "secrets.nix" -o \
  -name "server.conf" -o \
  -name "secret.toml" \
\) | grep -v backups | grep -v '\.enc$' | while read -r file; do
  enc_file="${file}.enc"
  echo "Encrypting $file → $enc_file"
  sops -e "$file" > "$enc_file"
  git add "$enc_file"
done
