[insecure]
ru1-root ansible_host=ru1.lxft.dev ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519
de1-root ansible_host=de1.lxft.dev ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519

[secure]
de1 ansible_host=de1.lxft.dev ansible_user=main ansible_ssh_private_key_file=~/.ssh/id_ed25519
ru1 ansible_host=ru1.lxft.dev ansible_user=main ansible_ssh_private_key_file=~/.ssh/id_ed25519

[de]
de1

[ru]
ru1
